name: build

on:
  push:
    branches:
    - 'main'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0         
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: https://github.com/docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: https://github.com/docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PWD }}
    - name: Build image and push to Docker Hub
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 -q --push . -t buddyspencer/ubuntu-node:latest
      volumes:
      - /var/run/docker.sock:/var/run/docker.sock